
import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { MessageCircle, X, Send, Code2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { base44 } from "@/api/base44Client";
import ReactMarkdown from "react-markdown";

const napzPersonality = {
  greetings: [
    "Hello! I'm Napz, powered by DeepSeek V3.1. I write complete, production-ready code in HTML, CSS, JavaScript, Python, React, and more. Describe what you want to build!",
    "Hi! Napz here, running on DeepSeek V3.1 - the world's best coding AI. Tell me what you need and I'll write full implementations for you.",
    "Welcome! I'm Napz, your AI coding partner powered by DeepSeek V3.1. Describe your project and I'll provide complete, working code."
  ]
};

export default function NapzChatbot() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [user, setUser] = useState(null);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    if (isOpen) {
      loadUser();
      if (messages.length === 0) {
        setTimeout(() => {
          addNapzMessage(napzPersonality.greetings[Math.floor(Math.random() * napzPersonality.greetings.length)]);
        }, 500);
      }
    }
  }, [isOpen]);

  const loadUser = async () => {
    try {
      const currentUser = await base44.auth.me();
      setUser(currentUser);
    } catch (error) {
      setUser(null);
    }
  };

  const addNapzMessage = (text) => {
    setMessages(prev => [...prev, { text, isNapz: true, timestamp: new Date() }]);
  };

  const addUserMessage = (text) => {
    setMessages(prev => [...prev, { text, isNapz: false, timestamp: new Date() }]);
  };

  const getResponse = async (userMessage) => {
    const lowerMsg = userMessage.toLowerCase();
    
    // Check for basic greetings
    if ((lowerMsg.includes("hello") || lowerMsg.includes("hi") || lowerMsg.includes("hey")) && lowerMsg.length < 20) {
      return "Hello! I'm powered by DeepSeek V3.1 - I can write complete code implementations for you. Tell me what website or feature you want to build!";
    } else if (lowerMsg.includes("thanks") || lowerMsg.includes("thank")) {
      return "You're welcome! Feel free to ask me to write more code or modify what I've created.";
    }
    
    // Chatbot is now FREE - no usage check!
    
    // Check if user should get watermark (same logic as terminal)
    const shouldAddWatermark = !user || 
                               user.role !== 'admin' && 
                               (!user.subscription_tier || 
                                user.subscription_tier === 'free');
    
    const watermarkNote = shouldAddWatermark 
      ? '\n\n🎨 WATERMARK INSTRUCTION: Since this is a free user, add this comment at the top of all code blocks:\n/* 🚀 Generated by NetNapz Free - Upgrade at netnapz.com/pricing */' 
      : '';
    
    // Use DeepSeek V3.1 via OpenRouter for FREE chatbot!
    try {
      const { data } = await base44.functions.invoke('deepseekSearch', {
        prompt: `You are Napz, an expert web development assistant powered by DeepSeek V3.1 who writes complete, production-ready code for users.

Your role:
- Write FULL, COMPLETE code implementations (not just snippets)
- Provide working HTML, CSS, JavaScript, React, Python, or any requested language
- Explain the code you write clearly
- Include all necessary code with proper structure
- Use modern best practices and clean code principles
- Always use proper markdown code blocks with language tags${watermarkNote}

User request: "${userMessage}"

Instructions:
1. Analyze what the user wants to build
2. Write COMPLETE, WORKING code - not just examples or snippets
3. If they want a website, provide full HTML structure with CSS and JavaScript
4. If they want a component, write the entire component
5. If they want backend code, write the full implementation
6. Use proper markdown code blocks with language specification (e.g., \`\`\`html, \`\`\`css, \`\`\`javascript, \`\`\`python)
7. Explain what the code does and how to use it
8. Make the code production-ready and well-commented

Format: Write the complete code with explanations. Use multiple code blocks if needed for different files (HTML, CSS, JS).

Write professional, complete implementations that users can copy and use immediately.`
      });

      if (data.error) {
        return "⚠️ Error: " + data.error;
      }

      return data.response;
    } catch (error) {
      console.error('Chatbot error:', error);
      return "I encountered an error. Please describe what code you'd like me to write and I'll help you build it.";
    }
  };

  const handleSend = async () => {
    if (!inputValue.trim()) return;

    const userMsg = inputValue;
    setInputValue("");
    addUserMessage(userMsg);
    
    setIsTyping(true);
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const response = await getResponse(userMsg);
    setIsTyping(false);
    addNapzMessage(response);
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <>
      {/* Floating Button */}
      <AnimatePresence>
        {!isOpen && (
          <motion.button
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0, opacity: 0 }}
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setIsOpen(true)}
            className="fixed bottom-6 right-6 w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full shadow-2xl flex items-center justify-center z-50 group hover:shadow-blue-500/50 transition-all duration-300"
          >
            <div className="absolute inset-0 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full blur-xl opacity-50 group-hover:opacity-75 transition-opacity"></div>
            <Code2 className="w-7 h-7 text-white relative z-10" />
            <div className="absolute -top-1 -right-1 w-5 h-5 bg-green-500 rounded-full border-2 border-white flex items-center justify-center">
              <Sparkles className="w-3 h-3 text-white" />
            </div>
          </motion.button>
        )}
      </AnimatePresence>

      {/* Chat Window */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 100, scale: 0.8 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 100, scale: 0.8 }}
            transition={{ type: "spring", damping: 25 }}
            className="fixed bottom-6 right-6 w-96 h-[600px] max-h-[80vh] glass border border-gray-200/50 dark:border-gray-700/50 rounded-3xl shadow-2xl z-50 flex flex-col overflow-hidden"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-blue-500 to-purple-600 p-6 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="relative">
                  <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center shadow-lg">
                    <Code2 className="w-6 h-6 text-blue-600" />
                  </div>
                  <div className="absolute -bottom-1 -right-1 w-4 h-4 bg-green-500 rounded-full border-2 border-white"></div>
                </div>
                <div>
                  <h3 className="font-bold text-white text-lg">Napz</h3>
                  <p className="text-xs text-blue-100 flex items-center gap-1">
                    <Sparkles className="w-3 h-3" />
                    DeepSeek V3.1 - FREE
                  </p>
                </div>
              </div>
              <button
                onClick={() => setIsOpen(false)}
                className="w-8 h-8 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-colors"
              >
                <X className="w-5 h-5 text-white" />
              </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-6 space-y-4 bg-gray-50/50 dark:bg-gray-900/50">
              {/* Free tier notice */}
              {user && (!user.subscription_tier || user.subscription_tier === 'free') && messages.length === 1 && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="bg-blue-500/20 border border-blue-500/30 rounded-xl p-3 text-center mb-4"
                >
                  <p className="text-xs text-blue-300">
                    💬 Free tier: Code includes watermarks. <a href="/Pricing" className="underline font-bold">Upgrade</a> for clean code!
                  </p>
                </motion.div>
              )}
              
              {messages.map((msg, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex ${msg.isNapz ? "justify-start" : "justify-end"}`}
                >
                  <div
                    className={`max-w-[85%] rounded-2xl px-4 py-3 ${
                      msg.isNapz
                        ? "bg-white dark:bg-gray-800 text-gray-900 dark:text-white border border-gray-200 dark:border-gray-700"
                        : "bg-gradient-to-r from-blue-500 to-purple-600 text-white"
                    }`}
                  >
                    {msg.isNapz && (
                      <div className="flex items-center gap-2 mb-2">
                        <Code2 className="w-3 h-3 text-blue-500" />
                        <span className="text-xs font-bold text-gray-500 dark:text-gray-400">Napz Code Writer</span>
                      </div>
                    )}
                    {msg.isNapz ? (
                      <div className="prose prose-sm dark:prose-invert max-w-none">
                        <ReactMarkdown
                          components={{
                            code: ({ inline, className, children }) => {
                              const match = /language-(\w+)/.exec(className || '');
                              const language = match ? match[1] : '';
                              return !inline && match ? (
                                <div className="relative group my-3">
                                  {language && (
                                    <div className="absolute top-0 right-0 px-2 py-1 bg-gray-700 text-gray-300 text-xs rounded-bl-lg rounded-tr-lg font-mono">
                                      {language}
                                    </div>
                                  )}
                                  <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 overflow-x-auto text-xs leading-relaxed">
                                    <code className={className}>{children}</code>
                                  </pre>
                                </div>
                              ) : (
                                <code className="px-1.5 py-0.5 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded text-xs font-mono">
                                  {children}
                                </code>
                              );
                            },
                            p: ({ children }) => <p className="text-sm leading-relaxed mb-2">{children}</p>,
                            ul: ({ children }) => <ul className="list-disc list-inside space-y-1 text-sm mb-2">{children}</ul>,
                            ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 text-sm mb-2">{children}</ol>,
                            li: ({ children }) => <li className="text-sm">{children}</li>,
                            h1: ({ children }) => <h1 className="font-bold text-base mt-3 mb-2">{children}</h1>,
                            h2: ({ children }) => <h2 className="font-bold text-sm mt-3 mb-2">{children}</h2>,
                            h3: ({ children }) => <h3 className="font-bold text-sm mt-2 mb-1">{children}</h3>,
                            strong: ({ children }) => <strong className="font-semibold text-blue-600 dark:text-blue-400">{children}</strong>,
                            blockquote: ({ children }) => (
                              <blockquote className="border-l-3 border-blue-500 pl-3 py-1 my-2 bg-blue-50 dark:bg-blue-900/20 text-sm italic">
                                {children}
                              </blockquote>
                            ),
                          }}
                        >
                          {msg.text}
                        </ReactMarkdown>
                      </div>
                    ) : (
                      <p className="text-sm leading-relaxed">{msg.text}</p>
                    )}
                  </div>
                </motion.div>
              ))}
              
              {isTyping && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex justify-start"
                >
                  <div className="bg-white dark:bg-gray-800 rounded-2xl px-6 py-3 border border-gray-200 dark:border-gray-700">
                    <div className="flex gap-1 items-center">
                      <Code2 className="w-4 h-4 text-blue-500 animate-pulse mr-2" />
                      <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></div>
                      <div className="w-2 h-2 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></div>
                      <div className="w-2 h-2 bg-pink-500 rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></div>
                    </div>
                  </div>
                </motion.div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <div className="p-4 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
              <div className="flex gap-2">
                <Input
                  id="napz-message"
                  type="text"
                  autoComplete="off"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder="Describe the website you want to build..."
                  className="flex-1 rounded-xl border-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-400"
                  aria-label="Code request"
                />
                <Button
                  onClick={handleSend}
                  disabled={!inputValue.trim()}
                  className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white rounded-xl px-4"
                  aria-label="Send code request"
                >
                  <Send className="w-4 h-4" />
                </Button>
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-2 text-center">
                🤖 Powered by DeepSeek V3.1 - Unlimited FREE code generation
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
